version: '3.0'
services:
  # app:
  #   build: .
  #   env_file: .env
  #   command: 'npm run start:dev'
  #   volumes:
  #     - /app/node_modules
  #   ports:
  #     - 3030:3030

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/

  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - 5432:5432

volumes:
  redis:
  postgres:
